// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtg5qMT0q1sHoIPoG0RGRwm0SIwTdjn70',
    appId: '1:160300533135:web:698121cb9b479d0de037fa',
    messagingSenderId: '160300533135',
    projectId: 'flutter-d0b01',
    authDomain: 'flutter-d0b01.firebaseapp.com',
    storageBucket: 'flutter-d0b01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4BEU_2x2lNUaXmUifhBerAkuvhMAH_iU',
    appId: '1:160300533135:android:41b77677fbaf22ace037fa',
    messagingSenderId: '160300533135',
    projectId: 'flutter-d0b01',
    storageBucket: 'flutter-d0b01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2-nTUcBoUycyPlLJq0PuZilH8ycPG-Q',
    appId: '1:160300533135:ios:ade01ec630f4c0fae037fa',
    messagingSenderId: '160300533135',
    projectId: 'flutter-d0b01',
    storageBucket: 'flutter-d0b01.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2-nTUcBoUycyPlLJq0PuZilH8ycPG-Q',
    appId: '1:160300533135:ios:ade01ec630f4c0fae037fa',
    messagingSenderId: '160300533135',
    projectId: 'flutter-d0b01',
    storageBucket: 'flutter-d0b01.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtg5qMT0q1sHoIPoG0RGRwm0SIwTdjn70',
    appId: '1:160300533135:web:1369f1686b7b7f64e037fa',
    messagingSenderId: '160300533135',
    projectId: 'flutter-d0b01',
    authDomain: 'flutter-d0b01.firebaseapp.com',
    storageBucket: 'flutter-d0b01.firebasestorage.app',
  );
}
